# QuickBooks Sync Service Configuration

[quickbooks]
# How to connect to QuickBooks company file:
# Options:
#   1. Specific file path: "C:\\Users\\YourUser\\Documents\\QuickBooks\\Your Company.qbw"
#   2. Use currently open file: "AUTO"
#   3. Empty string: Will prompt to select from available files
#   4. Mock data for testing: "MOCK"
company_file = "F:\\QB File\\alderac entertainment group.qbw"

# Application name registered with QuickBooks (must match exactly)
# This is the name you used when you first registered your application with QuickBooks
application_name = "QuickBooks Sync Service"

# Application ID (GUID) provided by QuickBooks during registration
# This is the unique identifier for your application
application_id = ""

# Connection mode preference (optional)
# Options:
#   "multi-user" - Prioritize multi-user mode (recommended for production)
#   "single-user" - Prioritize single-user mode
#   "auto" - Try all modes automatically (default)
connection_mode = "multi-user"

# Google Sheets Sync Configuration

[google_sheets]
# Google Apps Script Web App URL
webapp_url = "https://script.google.com/macros/s/AKfycbzn3s0BkjLwRyVNQP3Wd44qHsp2X_LIBTnbCg4Bxw-p1d-dJ57_pm9XZRFqUSO46RqAJQ/exec"
# API key for authentication
api_key = "bd1eab31-c63e-495d-9469-4fc06b1adb0d"

# This is the Profit Workshop
[[sync_block]]
spreadsheet_id = "1zwDqSpJ0WvYFDhaG35TkUNfEq3ZOXiAQxODx2_nzSQk"
# ACCOUNT FULL NAME IN QB
account_full_name = "Cash Accounts:BoA Accounts:INCOME TAX"
# SHEET NAME (the tab within the document)
sheet_name = "The Simple Buckets"
# CELL ADDRESS (where to write the balance)
cell_address = "D5"

# This is the Profit Workshop
[[sync_block]]
spreadsheet_id = "1zwDqSpJ0WvYFDhaG35TkUNfEq3ZOXiAQxODx2_nzSQk"
# ACCOUNT FULL NAME IN QB
account_full_name = "Cash Accounts:BoA Accounts:PROFIT Vault:Profit"
# SHEET NAME (the tab within the document)
sheet_name = "The Simple Buckets"
# CELL ADDRESS (where to write the balance)
cell_address = "D14"

# This is the Profit Workshop
[[sync_block]]
spreadsheet_id = "1zwDqSpJ0WvYFDhaG35TkUNfEq3ZOXiAQxODx2_nzSQk"
# ACCOUNT FULL NAME IN QB
account_full_name = "Cash Accounts:BoA Accounts:PROFIT Vault:Shareholders"
# SHEET NAME (the tab within the document)
sheet_name = "The Simple Buckets"
# CELL ADDRESS (where to write the balance)
cell_address = "D15"

# This is the Profit Workshop
[[sync_block]]
spreadsheet_id = "1zwDqSpJ0WvYFDhaG35TkUNfEq3ZOXiAQxODx2_nzSQk"
# ACCOUNT FULL NAME IN QB
account_full_name = "Cash Accounts:BoA Accounts:PROFIT Vault:Safety Reserve"
# SHEET NAME (the tab within the document)
sheet_name = "The Simple Buckets"
# CELL ADDRESS (where to write the balance)
cell_address = "D17"

# This is the Profit Workshop
[[sync_block]]
spreadsheet_id = "1zwDqSpJ0WvYFDhaG35TkUNfEq3ZOXiAQxODx2_nzSQk"
# ACCOUNT FULL NAME IN QB
account_full_name = "Cash Accounts:BoA Accounts:PROFIT Vault:Profit Share"
# SHEET NAME (the tab within the document)
sheet_name = "The Simple Buckets"
# CELL ADDRESS (where to write the balance)
cell_address = "D16"
