# QuickBooks to Google Sheets Sync Configuration

[quickbooks]
# How to connect to QuickBooks company file:
# Options:
#   1. Specific file path: "C:\\Users\\YourUser\\Documents\\QuickBooks\\Your Company.qbw"
#   2. Use currently open file: "AUTO"
#   3. Empty string: Will prompt to select from available files
#   4. Mock data for testing: "MOCK"
company_file = "AUTO"
# Account number to sync
account_number = "9445"
# Account name for logging/identification
account_name = "INCOME TAX"

# Application name registered with QuickBooks (must match exactly)
# This is the name you used when you first registered your application with QuickBooks
application_name = "QuickBooks Sync Service"

# Application ID (GUID) provided by QuickBooks during registration
# This is the unique identifier for your application
application_id = ""

# Connection mode preference (optional)
# Options:
#   "multi-user" - Prioritize multi-user mode (recommended for production)
#   "single-user" - Prioritize single-user mode
#   "auto" - Try all modes automatically (default)
connection_mode = "multi-user"

# QuickBooks Authentication (optional)
# Most users can leave these empty - see AUTHENTICATION.md for details

# Company file password (if your .qbw file is password-protected)
# Can also use environment variable: QB_FILE_PASSWORD
company_file_password = ""

# QuickBooks user credentials (for multi-user files only)
# Can also use environment variables: QB_USERNAME and QB_USER_PASSWORD
qb_username = ""
qb_password = ""

# Connection timeout in seconds
connection_timeout = 30

[google_sheets]
# Google Apps Script Web App URL
webapp_url = "https://script.google.com/macros/s/AKfycbz1yVgVctgWOfyLAr95vXjXYSXjFtGl6OVqU_ljKUgPJakGoZ5tWnSvlc9XLq6tTddp1w/exec"
# API key for authentication
api_key = "30999370-950f-4a87-b2fb-54670dffdf5f"
# SPREADSHEET ID (the document itself)
spreadsheet_id = "1zwDqSpJ0WvYFDhaG35TkUNfEq3ZOXiAQxODx2_nzSQk"
# SHEET NAME (the tab within the document)
sheet_name = "The Simple Buckets"
# CELL ADDRESS (where to write the balance)
cell_address = "D5"


[schedule]
# Cron expression for sync schedule
# "0 0 * * * *" = every hour at minute 0
# "0 */30 * * * *" = every 30 minutes
# "0 0 */6 * * *" = every 6 hours
cron_expression = "0 0 * * * *"
