# QuickBooks Sync Service Configuration

[quickbooks]
# How to connect to QuickBooks company file:
# Options:
#   1. Specific file path: "C:\\Users\\YourUser\\Documents\\QuickBooks\\Your Company.qbw"
#   2. Use currently open file: "AUTO"
#   3. Empty string: Will prompt to select from available files
#   4. Mock data for testing: "MOCK"
company_file = "F:\\QB File\\alderac entertainment group.qbw"

# Application name registered with QuickBooks (must match exactly)
# This is the name you used when you first registered your application with QuickBooks
application_name = "QuickBooks Sync Service"

# Application ID (GUID) provided by QuickBooks during registration
# This is the unique identifier for your application
application_id = ""

# Connection mode preference (optional)
# Options:
#   "multi-user" - Prioritize multi-user mode (recommended for production)
#   "single-user" - Prioritize single-user mode
#   "auto" - Try all modes automatically (default)
connection_mode = "multi-user"

# Google Sheets Sync Configuration

[google_sheets]
# Google Apps Script Web App URL
webapp_url = "https://script.google.com/macros/s/AKfycbztC80vrEJEWviz15r1cC9rTVJfYTVdl6qk1SIAgfW0_Oth8n-BrehYh33xjI9y14rDSg/exec"
# API key for authentication
api_key = "5db8c2c0-8909-4bc7-803e-6b95f21628e9"
# SPREADSHEET ID (the document itself)
spreadsheet_id = "1zwDqSpJ0WvYFDhaG35TkUNfEq3ZOXiAQxODx2_nzSQk"
# SHEET NAME (the tab within the document)
sheet_name = "The Simple Buckets"
# CELL ADDRESS (where to write the balance)
cell_address = "D5"
