# QuickBooks Sync Service Configuration

[quickbooks]
# How to connect to QuickBooks company file:
# Options:
#   1. Specific file path: "C:\\Users\\YourUser\\Documents\\QuickBooks\\Your Company.qbw"
#   2. Use currently open file: "AUTO"
#   3. Empty string: Will prompt to select from available files
#   4. Mock data for testing: "MOCK"
company_file = "AUTO"

# Application name registered with QuickBooks (must match exactly)
# This is the name you used when you first registered your application with QuickBooks
application_name = "QuickBooks Sync Service"

# Application ID (GUID) provided by QuickBooks during registration
# This is the unique identifier for your application
application_id = ""

# Connection mode preference (optional)
# Options:
#   "multi-user" - Prioritize multi-user mode (recommended for production)
#   "single-user" - Prioritize single-user mode
#   "auto" - Try all modes automatically (default)
connection_mode = "multi-user"